# Azure Vote UI control
title: "Azure Vote App"
value1: ladies
value2: gentlemen
global:
  azure:
    images:
      frontend:
        digest: sha256:f75a661ac0dd9711bc602837840f742dfd68e4ea74c4251416c5480d8f85d93c
        image: azure-vote-front
        registry: azurek8ssamples.azurecr.io/marketplaceimages
      backend:
        digest: sha256:f6e3da94f24dabc9569204c774cd7d11ab6eaa3865b108ae07694161251c854c
        image: azure-vote-back
        registry: azurek8ssamples.azurecr.io/marketplaceimages
# how many frontends do we want?
replicaCount: 1

# Service controls
serviceNameFront: azure-vote-front
serviceType: LoadBalancer